include:
  - ~/shvirtd-example-python/proxy.yaml

version: "3"

services:
  web:
    build: .
    restart: always
    networks: ["backend"]


  db:
     image: mysql:8
     restart: always
     networks: ["backend"]
     


networks:
  backend:
    name: backend
    driver: bridge




  














networks:
  backend
    
    
    

  
